{
 "title": "Tom_Power",
 "time": { "from": "2022-11-07T15:36:36.970Z", "to": "2022-11-07T15:44:53.521Z" },
 "panels": [
  {
   "title": "System Input Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "PowerEdge_PowerMetrics_SystemInputPower",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Total % Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "PhysicalCpu_Total_%UtilTime", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total CPU Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "PowerEdge_PowerMetrics_TotalCPUPower",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(PowerEdge_PowerMetrics_TotalCPUPower)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "%C0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "PCPUPowerStatePCPU0_%C-StateC0", "legendFormat": "__auto" },
    { "expr": "PCPUPowerStatePCPU1_%C-StateC0", "legendFormat": "__auto" },
    { "expr": "PCPUPowerStatePCPU2_%C-StateC0", "legendFormat": "__auto" },
    { "expr": "PCPUPowerStatePCPU3_%C-StateC0", "legendFormat": "__auto" },
    { "expr": "PCPUPowerStatePCPU4_%C-StateC0", "legendFormat": "__auto" },
    { "expr": "PCPUPowerStatePCPU5_%C-StateC0", "legendFormat": "__auto" },
    { "expr": "PCPUPowerStatePCPU6_%C-StateC0", "legendFormat": "__auto" },
    { "expr": "PCPUPowerStatePCPU7_%C-StateC0", "legendFormat": "__auto" },
    { "expr": "PCPUPowerStatePCPU8_%C-StateC0", "legendFormat": "__auto" },
    { "expr": "PCPUPowerStatePCPU9_%C-StateC0", "legendFormat": "__auto" },
    {
     "expr": "PCPUPowerStatePCPU10_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU11_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU12_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU13_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU14_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU15_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU16_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU17_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU18_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU19_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU20_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU21_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU22_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU23_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU24_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU25_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU26_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU27_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU28_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU29_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU30_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU31_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU32_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU33_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU34_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU35_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU36_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU37_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU38_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU39_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU40_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU41_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU42_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU43_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU44_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU45_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU46_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU47_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU48_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU49_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU50_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU51_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU52_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU53_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU54_%C-StateC0",
     "legendFormat": "__auto"
    },
    {
     "expr": "PCPUPowerStatePCPU55_%C-StateC0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}